kind: Service
apiVersion: v1
metadata:
  name: front-k8s-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 90
    targetPort: 80
    nodePort: 30003
  selector:
    app: front-k8s
