apiVersion: apps/v1
kind: Deployment
metadata: #api name and labels
  name: spring-k8s
spec:
  replicas: 2
  selector:
    matchLabels: #name singale service
      app: spring-k8s
  template: #template info
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
        - name: spring-k8s #images name
          image: k8sapp:latest
          imagePullPolicy: Never #Never
          ports:
            - containerPort: 8085
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres_db
            - name: DB_USERNAME
              value: savasdb
            - name: DB_PASSWORD
              value: savasdb123