apiVersion: v1
kind: Service #service object
metadata:
  name: spring-k8s-service
spec:
  selector:
    app: spring-k8s
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8085 #exposed service port
      nodePort: 30002
  type: LoadBalancer #NodePort
