apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: database
subsets:
  - addresses:
      - ip: "23.99.34.75" #db sunucu ip
    ports:
      - port: 5432